name: flytt
description: A ride-sharing application called Flytt.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Your existing dependencies
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  provider: ^6.1.1
  google_maps_flutter: ^2.5.0
  flutter_dotenv: ^5.2.1
  geolocator: ^10.0.1
  google_places_flutter: ^2.0.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_polyline_algorithm: ^3.1.0
  http: ^0.13.6
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.3.4
  flutter_contacts: ^1.1.7+1
  
  # PDF dependencies - make sure these are included
  path_provider: ^2.1.3
  pdf: ^3.11.0

  cupertino_icons: ^1.0.2
  phone_numbers_parser: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/icon/icon.png
    - assets/icon/logo.png  # Make sure this file exists!
    - assets/icon/pin.png
    - assets/fonts/
    - assets/cards/
    - assets/flags/
    - assets/2Wheels/
    - assets/onboarding/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#1A1723"
  adaptive_icon_foreground: "assets/icon/icon.png"